#!/usr/bin/env python3
import sys
import os

script_path = os.path.realpath(__file__)
script_dir = os.path.dirname(script_path)
main_path = os.path.join(script_dir, "main.py")

os.chdir(script_dir)
sys.path.insert(0, script_dir)

os.execv(sys.executable, [sys.executable, main_path] + sys.argv[1:])
