ai_shell:
  classification_confidence_threshold: 0.7
  classifier_commands: 3
  context_commands: 5
  max_history: 50
  max_output_length: 1000
chromadb:
  distance_metric: cosine
  hnsw_construction_ef: 200
  hnsw_m: 16
  hnsw_search_ef: 10
  hnsw_space: cosine
embedding:
  model: all-MiniLM-L6-v2
keep_last: 20
llm_configs:
  agent_llm: gpt_5
  classifier_llm: gpt_4_1
llm_providers:
  gpt_4_1:
    base_url: https://openrouter.ai/api/v1
    max_retries: 3
    model: openai/gpt-4.1-mini
    temperature: 0.1
    timeout: 30
  gpt_5:
    base_url: https://openrouter.ai/api/v1
    max_retries: 3
    model: openai/gpt-4.1-mini
    reasoning_effort: medium
    temperature: 0.5
    timeout: 20
    verbosity: medium
  qwen3_next:
    base_url: https://openrouter.ai/api/v1
    max_retries: 3
    max_tokens: 32768
    model: Qwen/Qwen3-Next-80B-A3B-Thinking
    response_parser: qwen_thinking
    temperature: 0.6
    timeout: 120
    top_p: 0.95
max_steps: 50
rag:
  fallback_chunks: 10
  max_chunks: 10
  similarity_threshold: 0.3
